spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: cainiaooj-backend-user-service
          uri: lb://cainiaooj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: cainiaooj-backend-question-service
          uri: lb://cainiaooj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: cainiaooj-backend-judge-service
          uri: lb://cainiaooj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: cainiaooj-backend-ai-service
          uri: lb://cainiaooj-backend-ai-service
          predicates:
            - Path=/api/ai/**
  application:
    name: cainiaooj-backend-gateway
  # 这个是因为spring-cloud-gateway背后是javaWebFlux实现的，和springMVC不兼容
  # 我们要么在gateway的pom中排除掉父模块的springmvc，要么就用这个配置
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
