# ??????
# @author <a href="https://github.com/liyupi">?????</a>
# @from <a href="https://yupi.icu">????????</a>
spring:
  application:
    name: cainiaooj-backend-ai-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  ai:
    dashscope:
      api-key:
      chat:
        options:
          model: qwen3-coder-plus
  # session ??
  # ?????
  # todo ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ojSystem
    username: root
    password:
  # Redis ??
  # todo ????????????
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  # Elasticsearch ??
  # todo ????????????
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # ????
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8105
  servlet:
    context-path: /api/ai
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ??????

